apiVersion: v1
kind: Service
metadata:
  name: deception-engine
  namespace: capstone-deception
spec:
  selector:
    app: deception-engine
  ports:
    - name: http
      port: 8001
      targetPort: 8001
