apiVersion: apps/v1
kind: Deployment
metadata:
  name: deception-engine
  namespace: capstone-deception
  labels:
    app: deception-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deception-engine
  template:
    metadata:
      labels:
        app: deception-engine
    spec:
      containers:
        - name: deception-engine
          image: capstone-deception-engine:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          readinessProbe:
            httpGet:
              path: /ready
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
