apiVersion: apps/v1
kind: Deployment
metadata:
  name: deception-engine
  namespace: capstone-deception
  labels:
    app: deception-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deception-engine
  template:
    metadata:
      labels:
        app: deception-engine
    spec:
      containers:
        - name: deception-engine
          image: capstone-main-deception-engine:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: REDIS_HOST
              value: redis-deception
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 384Mi
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8001
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
