apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: deception-engine-prometheus-scaler
  namespace: capstone-deception
spec:
  scaleTargetRef:
    name: deception-engine

  pollingInterval: 15
  cooldownPeriod: 120
  minReplicaCount: 1
  maxReplicaCount: 10

  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 30
          policies:
            - type: Pods
              value: 2
              periodSeconds: 30
        scaleDown:
          stabilizationWindowSeconds: 120
          policies:
            - type: Pods
              value: 1
              periodSeconds: 120

  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus:9090
        metricName: capstone_scaling_scale_pressure
        query: capstone_scaling_scale_pressure
        threshold: "0.6"
        activationThreshold: "0.3"
