apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: deception-engine-prometheus-scaler
  namespace: capstone-deception
spec:
  scaleTargetRef:
    name: deception-engine

  pollingInterval: 5
  cooldownPeriod: 120
  minReplicaCount: 1
  maxReplicaCount: 10

  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 2
              periodSeconds: 30
        scaleDown:
          stabilizationWindowSeconds: 120
          policies:
            - type: Percent
              value: 100
              periodSeconds: 60

  triggers:
    - type: prometheus
      metricType: AverageValue
      metadata:
        serverAddress: http://prometheus.capstone-deception.svc.cluster.local:9090
        metricName: capstone_scaling_current_replicas
        query: capstone_scaling_current_replicas
        threshold: "1"
        activationThreshold: "0"
